# Site settings
title: Higham Hill Hub
email: info@highamhillhub.org.uk
description: > # this means to ignore newlines until "baseurl:"
  Higham Hill Hub is an exciting new community space in the heart of 
  Higham Hill. Our facilities include a hall with sprung floor, 
  small kitchen, toilets (incl disabled toilet), meeting room and a large, 
  private lawn. The Hub is affordable to hire for everything from 
  classes to meetings to birthday parties.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://highamhillhub.org.uk" # the base hostname & protocol for your site
twitter_username: 
github_username:  sarigriffiths
facebook_url: https://www.facebook.com/highamhillhub

# Build settings
markdown: kramdown
